<<<<<<< HEAD:Online Education/Migrations/202006131900205_first.Designer.cs
// <auto-generated />
namespace Online_Education.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class first : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first));
        
        string IMigrationMetadata.Id
        {
            get { return "202006131900205_first"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
||||||| merged common ancestors:Online Education/Migrations/202006112301045_bb.Designer.cs
// <auto-generated />
namespace Online_Education.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bb));
        
        string IMigrationMetadata.Id
        {
            get { return "202006112301045_bb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
=======
// <auto-generated />
namespace Online_Education.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class s : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(s));
        
        string IMigrationMetadata.Id
        {
            get { return "202006132112497_s"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
>>>>>>> 1cfb942736b654c3553d5dfaa341448e574cb73e:Online Education/Migrations/202006132112497_s.Designer.cs
